In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import keras.backend as K
from keras.models import Sequential,model_from_json
from keras.layers import Dense
from keras.optimizers import SGD, Adam
from sklearn.model_selection import train_test_split
import scipy.io as io

Using TensorFlow backend.


In [2]:
json_file = open('crybaby.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

In [3]:
hungry = io.loadmat("hungry_ANN.mat")
spasm = io.loadmat("spasm_ANN.mat")
#SPASM = 1
#HUNGRY = 0

hungry_dataset = hungry['hungry']
spasm_dataser = spasm['spasm']

dataset=np.row_stack((hungry_dataset,spasm_dataser))
np.random.shuffle(dataset)
ip_shuff = np.delete(dataset, 50, 1)
op_shuff = dataset[:,50]

In [4]:
ip_shuff

array([[ 0.01556896,  0.06591106,  0.13655512, ...,  0.07072032,
         0.07572878,  0.07550688],
       [ 0.01334085,  0.0471112 ,  0.08924097, ...,  0.0511908 ,
         0.0608467 ,  0.06238517],
       [ 0.04304752,  0.11934009,  0.23672312, ...,  0.0196335 ,
         0.01942679,  0.02444532],
       ..., 
       [ 0.04087334,  0.11113501,  0.18522267, ...,  0.01864334,
         0.01976025,  0.02593414],
       [ 0.01528661,  0.06186272,  0.1265313 , ...,  0.07045907,
         0.07498202,  0.07206107],
       [ 0.04247649,  0.11895021,  0.24168531, ...,  0.01968873,
         0.01949603,  0.02459394]])

In [5]:
op_shuff

array([ 1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,
        0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,
        1.,  1.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,
        1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  1.,
        1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,
        1.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        1.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,
        1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0

In [6]:
loaded_model.predict_classes(ip_shuff)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    